import 'package:flutter/material.dart';

class AppColor{
  static const Color textColor=Color(0xfff4f1f8);
  static const Color textColorSecondary=Color(0xffe8e6de);
  static const Color textColorSecondary2 = Color(0xFF687077);
  static const Color textAccentColor=Color(0xfff3c6c6);
  static const Color textPrimaryColor=Color(0xffa7e7bb);
  static const Color textErrorColor=Color(0xffecc29c);
  static const Color textFieldColor=Color(0xff2c2d30);
  static const Color appBarColor=Color(0xff333c4d);
  static const Color backGroundColor=Color(0xff1f1f1f);
  static const Color backGroundColor1=Color(0xff1f1f1f);
  static const Color backGroundColor2=Color(0xff0e0e0e);
  static const Color primaryColor=Color(0xff1bc06e);
  static const Color secondaryColor=Color(0xFF2D3541);
  static const Color secondary10Color=Color(0xFF232933);
  static const Color secondary50Color=Color(0xff141a26);
  static const Color secondary100Color=Color(0xFF1f2b3e);
  static const Color secondary200Color=Color(0xFF1F3A5F);
  static const Color secondary300Color=Color(0xFF3180EA);
  static const Color secondary2Color=Color(0xff499fa2);
  static const Color secondary3Color=Color(0xff40b6ca);
  static const Color accentColor=Color(0xffe91e63);
  static const Color accent2Color=Color(0xFFFA114E);
  static const Color accent3Color=Color(0xFFC61C1C);
  static const Color purpleColor=Color(0xff50068d);
  static const Color buttonColor=Color(0xff02807e);
  static const Color circleColor=Color(0xff2f2b44);
  static const Color iconViewColor=Color(0xff969696);
  static const Color circularLoadingColor=Color(0xffdedad0);
  static const Color dividerColor=Color(0xffe3c477);
  static const Color successColor=Color(0xff04e86e);
  static const Color errorColor=Color(0xfff44336);
  //static const Color filterColor=Color(0xFF6200EA);
  static const Color filterColor=Color(0xFFAA00FF);
  static const Color baseColor=Color(0xFFC66FF6);
  static const Color goldDark = Color(0xFF7A5816);
  static const Color gold = Color(0xFFB48622);
}